---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:ItamarLevin/echo-flux
    path: charts/echo
    ref: master
  values:
    image:
      repository: slipperymuffin/echo
      tag: dev-228278f002480971dcf4869217a65dcbc9b960d8
    mongodb:
      enabled: false
      persist: false
    ingress:
      enabled: true
      annotations:
        #nginx.ingress.kubernetes.io/rewrite-target: /
        #nginx.org/proxy-connect-timeout: "9000s"
        cert-manager.io/issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: "nginx"

      hosts:
        - host: dev-hotwings.chickenkiller.com
          paths: [/]
      tls:
        - secretName: dev-echo-tls
          hosts:
            - dev-hotwings.chickenkiller.com