---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:1.0.*
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:ItamarLevin/echo-flux
    path: charts/echo
    ref: master
  values:
    image:
      repository: slipperymuffin/echo
      tag: 1.0.8
    mongodb:
      enabled: true
      # mongodb://username:password@mongodb.db:27017/echo
      url: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGIuZGI6MjcwMTcvZWNobw==
      persist: true
      dbname: echo