---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-staging
  namespace: staging
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:staging-*
spec:
  releaseName: echo-staging
  chart:
    git: git@github.com:ItamarLevin/echo-flux
    path: charts/echo
    ref: master
  values:
    image:
      repository: slipperymuffin/echo
      tag: staging-25b0de1adf33893e7dbf997db138ae6a3d95e3af
    mongodb:
      enabled: true
      # mongodb://username:password@mongodb.db:27017/echo-staging
      url: bW9uZ29kYjovL3VzZXJuYW1lOnBhc3N3b3JkQG1vbmdvZGIuZGI6MjcwMTcvZWNoby1zdGFnaW5n
      persist: true
      dbname: echo-staging
    ingress:
      enabled: true
      annotations:
        #nginx.ingress.kubernetes.io/rewrite-target: /
        #nginx.org/proxy-connect-timeout: "9000s"
        cert-manager.io/issuer: "letsencrypt-prod"
        kubernetes.io/ingress.class: "nginx"

      hosts:
        - host: hotwings94.chickenkiller.com
          paths: [/]
      tls:
        - secretName: echo-tls
          hosts:
            - hotwings94.chickenkiller.com
